### ISSUE TITLE
Problem with loading test #915 (Biccoca tests)

### ISSUE THREAD

**Issue by lopezcaraballoch** [lspestrip/striptease#105]
I deleted the file 00915.h5 of ~/.strip/unittests (as recommended). However, It is not automatically downloaded when I read it:
![view_procedure_solveProblem_4](https://github.com/lspestrip/striptease/assets/26574818/03365efc-e69b-4cb0-87b3-5b11d8b7fc3d)

Please, any other suggestion/recommendation?

Regards

**Comment by ziotom78** [comment]
You cannot delete a file without updating the internal database in `~/.strip/unittests/unittests.db`. Now that you have removed it, you should better delete the whole directory `~/.strip/unittests/` and re-run the command again.
