### ISSUE TITLE
Invert the calling order of `group` and `subgroup` in `load_hk`.

### ISSUE THREAD

**Issue by fincardona** [lspestrip/striptease#24]
The first input parameter of the `load_hk` method is `group` which is either `BIAS` or `DAQ`, while the second is `subgroup`, that can be either a polarimeter or a board name:
https://github.com/lspestrip/striptease/blob/921826363e797db4166a2c7de670c15a4e3eb292/striptease/hdf5files.py#L293
Instead, the first argument of `load_sci` is the polarimeter name:
https://github.com/lspestrip/striptease/blob/921826363e797db4166a2c7de670c15a4e3eb292/striptease/hdf5files.py#L332
It might be useful to invert the calling order of `group` and `subgroup` in `load_hk` to keep it coherent in the two methods.

**Comment by planck2007** [comment]
This choice has a meaning, strictly connected to the hardware architecture. In the electronics we have BIAS boards and Acquisition boards (DAQ). Each is connected to Polarimeters (either for bias or data acquisition).

For this reason Francesco asked to swap groups and subgroups, to reflect the actual hardware logic.
