### ISSUE TITLE
Installation in conda environment does not set properly the path

### ISSUE THREAD

**Issue by planck2007** [lspestrip/striptease#26]
After installation with python setup.py install in a conda environment striptease is not found unless running ipython from the parent directory

`(base) daniele@ladyday:~$ conda activate strip_env`
`(strip_env) daniele@ladyday:~$ cd Documents/LSPE/testing_integration/system_level_tests/striptease/`
`(strip_env) daniele@ladyday:~/Documents/LSPE/testing_integration/system_level_tests/striptease python setup.py install`
`running install`
`running build`
`running build_py`
`running install_lib`
`running install_egg_info`
`Removing /home/daniele/miniconda3/envs/strip_env/lib/python3.6/site-packages/Striptease-0.1.0-py3.6.egg-info`
`Writing /home/daniele/miniconda3/envs/strip_env/lib/python3.6/site-packages/Striptease-0.1.0-py3.6.egg-info`
`(strip_env) daniele@ladyday:~/Documents/LSPE/testing_integration/system_level_tests/striptease cd`
`(strip_env) daniele@ladyday:~ ipython`
`Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) `
`Type 'copyright', 'credits' or 'license' for more information`
`IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.`

`In [1]: import striptease`                         
`---------------------------------------------------------------------------`
`ModuleNotFoundError                       Traceback (most recent call last)`
`<ipython-input-1-d36e307df936> in <module>`
`----> 1 import striptease`

`ModuleNotFoundError: No module named 'striptease'`

`In [2]: `

**Comment by ziotom78** [comment]
Fixed by commit 2db7856.
