### ISSUE TITLE
Error in importing hdf5files

### ISSUE THREAD

**Issue by planck2007** [lspestrip/striptease#29]
When importing hdf5files from striptease there is an error "No module named 'hdf5files'". Example:
`import striptease`  -> No error
`from striptease import hdf5files` -> Error (no module named etc)

**Comment by ziotom78** [comment]
Works for me:

```sh
$ python -c "from striptease import hdf5files; print('ok')"
ok
$
```

Might it be related to bug #26 ? I implemented a fix in commit 2db7856, try to update your copy and try again.

**Comment by planck2007** [comment]
Updated copy, re-run setup.py install. From terminal it works. From Jupyter (opened from the same terminal where the command works) if I try to import striptease I get:

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2bf8c070cda6> in <module>
      1 #import os
      2 #os.chdir('/home/daniele/Documents/LSPE/testing_integration/system_level_tests/striptease')
----> 3 import striptease
      4 from importlib import reload
      5 reload(striptease)

~/miniconda3/envs/strip_env/lib/python3.6/site-packages/Striptease-0.1.0-py3.6.egg/striptease/__init__.py in <module>
     13 
     14 from urllib.parse import urljoin
---> 15 from web.rest.base import Connection
     16 
     17 # List of all the board names: handy if you need to iterate over them,

ModuleNotFoundError: No module named 'web.rest'`

**Comment by planck2007** [comment]
Update: the error appears also from a terminal if the folder is not the main striptease folder

**Comment by planck2007** [comment]
One more update: see example code (run in terminal with python launched from striptease main folder)
`In [1]: import striptease`                                                       
`In [2]: from striptease import hdf5files`                                       
`In [3]: from hdf5files import DataFile`                                 
`---------------------------------------------------------------------------`
`ModuleNotFoundError                       Traceback (most recent call last)`
`<ipython-input-3-61bbc69d0483> in <module>`
`----> 1 from hdf5files import DataFile`

`ModuleNotFoundError: No module named 'hdf5files'`

**Comment by ziotom78** [comment]
Still works for me:

# Jupyter

```sh
$ (virtualenv tmp && \
    . ./tmp/bin/activate && \
    cd striptease && \
    pip install -r requirements.txt && \
    python setup.py install && \
    python -c "import striptease" && \
    pip install jupyterlab && \
    jupyter-lab)
[lots of output, then Jupyter starts]
```

From Jupyter, I can load `striptease` successfully:

![striptease-troubleshooting](https://user-images.githubusercontent.com/377795/80494956-9143d500-8967-11ea-978f-798b8c6ccac7.png)

# Terminal

Still works for me:

```sh
$ cd /tmp && python3 -c "import striptease; print('Ok')"
Ok
$ which python3
/home/tomasi/Documents/work/LSPE/bologna/tmp/bin/python3
$ 
```

**Comment by planck2007** [comment]
Does not work for me:
```
(strip_env) daniele@ladyday:~/Documents/LSPE/testing_integration/system_level_tests/striptease$ cd /tmp && python3 -c "import striptease; print('Ok')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/daniele/miniconda3/envs/strip_env/lib/python3.6/site-packages/Striptease-0.1.0-py3.6.egg/striptease/__init__.py", line 15, in <module>
    from web.rest.base import Connection
ModuleNotFoundError: No module named 'web.rest'
(strip_env) daniele@ladyday:/tmp$ which python3
/home/daniele/miniconda3/envs/strip_env/bin/python3
(strip_env) daniele@ladyday:/tmp$ 
```
We have to find a way to understand this. How can I help?

**Comment by ziotom78** [comment]
> We have to find a way to understand this. How can I help?

It seems that some files were not copied in the `strip_env` environment. This was a bug (#26) that has been solved by commit 2db7856078f02651f4b9e0b3ddd4d8a421287523, so it seems that you are dealing with some old leftovers. Have you tried to completely wipe out `strip_env` and older copies of the `striptease` repository?

**Comment by planck2007** [comment]
I have not tried. What should I do exactly?

**Comment by ziotom78** [comment]
> I have not tried. What should I do exactly?

Run the following commands:

```bash
conda env remove strip_env
conda create -q -n strip_env
conda activate strip_env
conda install pyqt=5
pip install -r requirements.txt
python -m pip install -e .
```

Of course, if you need to use `ipython` and Jupyter, you must (re)install them within the `strip_env` environment.
