### ISSUE TITLE
Automatic login

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/striptease#3]
StripTEASE should contain two functions:

- One should read the username and password from some file in the user's home directory (e.g., `~/.StripTEASE_login`) and perform automatic authentication to the REST interface
- One should optionally read username and password from the same location and show a window asking the user either to confirm the username/password or to enter new ones, then it should perform authentication as above.

**Comment by stefano-sartor** [comment]
Connection Class looks for STRIP_USER, STRIP_PASSWORD env variables, then checks ~/.strip/conf.json for credentials.
widgets.login.LoginWidget can be used as pop-up dialog to collect credentials
