### ISSUE TITLE
Invalid HDF5 filename 

### ISSUE THREAD

**Issue by fincardona** [lspestrip/striptease#30]
Hi,

I used the script `join_hdf5.py` to join several h5 files and it worked very well! 
However, when I tried to open the file, I got the following error:
```
RuntimeError: Invalid HDF5 filename: undisturbed_clk_ref_0.h5
```
Then, I tried again by changing the filename from `undisturbed_clk_ref_0.h5` to a date-like format as `2022_04_24_22-27-50.h5` (date is intentionally fake), and it worked properly.

I was wondering whether it is possible to make the code working for any filename or, alternatively, how one is supposed to call the file when it contains data taken during a large time period (in my case, more than one day). 

Thanks!

**Comment by ziotom78** [comment]
Thanks, this should be fixed now.
