### ISSUE TITLE
Problems opening joined hdf5 files

### ISSUE THREAD

**Issue by luca-terenzi** [lspestrip/striptease#34]
when trying to read the joined pinchoff file the following message occurs:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Moduli_Analisi\StripTease\myenv\Scripts\striptease\striptease\hdf5files.py in parse_datetime_from_filename(filename)
    159             day=int(basename[8:10]),
--> 160             hour=int(basename[11:13]),
    161             minute=int(basename[14:16]),

ValueError: invalid literal for int() with base 10: 'pi'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Moduli_Analisi\StripTease\myenv\Scripts\striptease\striptease\hdf5files.py in __init__(self, filepath)
    251         try:
--> 252             self.datetime = parse_datetime_from_filename(self.filepath)
    253         except RuntimeError:

G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Moduli_Analisi\StripTease\myenv\Scripts\striptease\striptease\hdf5files.py in parse_datetime_from_filename(filename)
    164     except:
--> 165         raise RuntimeError(f"Invalid HDF5 filename: {filename}")
    166 

RuntimeError: Invalid HDF5 filename: G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Data\PinchOff\2020_05_06_pinchoff.h5

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Moduli_Analisi\StripTease\myenv\Scripts\striptease\striptease\hdf5files.py in parse_datetime_from_filename(filename)
    154     try:
--> 155         assert len(basename) == 22
    156         return datetime(

AssertionError: 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-a9a7b976bc82> in <module>
----> 1 my_data = DataFile(fname0)
      2 my_data.read_file_metadata()
      3 tags = my_data.tags
      4 #print(len(tags),tags[-1].name)
      5 #tags.append(my_data.tags[0])

G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Moduli_Analisi\StripTease\myenv\Scripts\striptease\striptease\hdf5files.py in __init__(self, filepath)
    258                 if "joined_files" in inpf and len(inpf["joined_files"]) > 0:
    259                     self.datetime = parse_datetime_from_filename(
--> 260                         str(inpf["joined_files"][0], encoding="utf-8")
    261                     )
    262                 else:

G:\Il mio Drive\DELL_BRIDGE\Luca\LSPE\Tests\System_Tests\Moduli_Analisi\StripTease\myenv\Scripts\striptease\striptease\hdf5files.py in parse_datetime_from_filename(filename)
    163         )
    164     except:
--> 165         raise RuntimeError(f"Invalid HDF5 filename: {filename}")
    166 
    167 

RuntimeError: Invalid HDF5 filename: file1.h5

**Comment by planck2007** [comment]
This is not a problem of the code, but of the filename that must respect a certain standard. Apparently the filename of the joined file was renamed by hand and fail to respect the requirement (it needs to end with the time). If you rename the file, for example, as `2020_05_06_02-27-50.h5` it will be opened correctly

**Comment by fincardona** [comment]
This issue is the same of https://github.com/lspestrip/striptease/issues/30 and it was closed by https://github.com/lspestrip/striptease/pull/31. Just try to update your `striptease` version by doing a `git pull`. Then, you should be able to assign to any joined hd5f file the name you prefer.

**Comment by ziotom78** [comment]
Federico is right, this issue was already corrected by commit #31 . To stay in touch with code developments, you can click the "watch" button at the top of this page: every time a user submits an issue or an issue is being closed, you'll receive an email. Nice and easy!
