### ISSUE TITLE
Housekeeping calibration

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/striptease#6]
There should be functions to convert data from ADU to physical units (e.g., A, mV) and vice versa.

**Comment by stefano-sartor** [comment]
[Calibration](https://github.com/lspestrip/striptease/blob/master/calibration/__init__.py) class stub created. It provides 2 methods: calibrate(pol,hk,value) to convert from ADU to physical units and reverse(pol,hk,value) to convert physical units to ADU
